# Generated by Django 6.1 on 2026-08-13 22:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('start_time', models.DateTimeField()),
                ('current_label', models.CharField(blank=True, max_length=255)),
                ('pickup_label', models.CharField(blank=True, max_length=255)),
                ('dropoff_label', models.CharField(blank=True, max_length=255)),
                ('total_distance_miles', models.FloatField(default=0)),
                ('total_duration_minutes', models.IntegerField(default=0)),
                ('route_geometry', models.JSONField(blank=True, default=list)),
                ('distances_estimated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('off_duty', 'Off_Duty'), ('sleeper_berth', 'Sleeper_Berth'), ('driving', 'Driving'), ('on_duty', 'On_Duty')], max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('miles', models.FloatField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_event_sequence_per_trip')],
            },
        ),
    ]
