# Generated by Django 6.1 on 2026-08-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_current_lat_trip_current_lon_trip_dropoff_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='no_road_route',
            field=models.BooleanField(default=False),
        ),
    ]
