# Generated by Django 6.1 on 2026-08-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_no_road_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
