# Generated by Django 6.1 on 2026-08-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='truck_routed',
            field=models.BooleanField(default=False),
        ),
    ]
