# Generated by Django 6.1 on 2026-08-15 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_truck_routed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='forced_stops',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='legs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='replanned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replans', to='trips.trip'),
        ),
    ]
