# Generated by Django 6.1 on 2026-08-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_forced_stops_trip_legs_trip_replanned_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='snapped_waypoints',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
