# Generated by Django 6.1 on 2026-08-16 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_snapped_waypoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='forced_stops',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='replanned_from',
        ),
    ]
